import { StyleSheet } from 'react-native';

export const colors = {
  background: '#ffffff',
  card: '#f5f5f5',
  cardBack: '#e8e8e8',
  primary: '#000000',
  primaryDark: '#222222',
  white: '#000000',
  grey: '#666666',
  lightGrey: '#e0e0e0',
  danger: '#cc0000',
  success: '#1a7a1a',
  border: '#dddddd',
  text: '#000000',
  textLight: '#ffffff',
};

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },

  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingTop: 50,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    backgroundColor: colors.background,
  },
  headerTitle: {
    color: colors.text,
    fontSize: 20,
    fontWeight: 'bold',
  },
  headerSubtitle: {
    color: colors.grey,
    fontSize: 13,
    marginTop: 2,
  },
  headerButtons: {
    flexDirection: 'row',
    gap: 8,
    alignItems: 'center',
  },
  addButton: {
    backgroundColor: colors.primary,
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  addButtonText: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: 'bold',
  },
  shuffleButton: {
    backgroundColor: colors.background,
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderWidth: 1.5,
    borderColor: colors.primary,
  },
  shuffleButtonText: {
    color: colors.primary,
    fontSize: 14,
    fontWeight: 'bold',
  },

  cardContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
  },
  counterText: {
    color: colors.grey,
    fontSize: 14,
    marginBottom: 20,
    textAlign: 'center',
  },
  card: {
    width: '100%',
    backgroundColor: colors.card,
    borderRadius: 20,
    padding: 28,
    minHeight: 220,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.border,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 10,
    elevation: 4,
  },
  cardBack: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  cardLabel: {
    color: colors.grey,
    fontSize: 12,
    fontWeight: 'bold',
    letterSpacing: 2,
    marginBottom: 16,
    textTransform: 'uppercase',
  },
  cardText: {
    color: colors.text,
    fontSize: 20,
    fontWeight: '600',
    textAlign: 'center',
    lineHeight: 30,
  },
  cardAnswerText: {
    color: '#ffffff',
    fontSize: 17,
    textAlign: 'center',
    lineHeight: 26,
  },

  showAnswerButton: {
    marginTop: 28,
    backgroundColor: colors.primary,
    borderRadius: 12,
    paddingVertical: 14,
    paddingHorizontal: 32,
  },
  showAnswerText: {
    color: '#ffffff',
    fontSize: 15,
    fontWeight: 'bold',
  },
  hideAnswerButton: {
    marginTop: 28,
    backgroundColor: colors.lightGrey,
    borderRadius: 12,
    paddingVertical: 14,
    paddingHorizontal: 32,
  },
  hideAnswerText: {
    color: colors.grey,
    fontSize: 15,
    fontWeight: 'bold',
  },

  navContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 24,
  },
  navButton: {
    backgroundColor: colors.lightGrey,
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 28,
  },
  navButtonDisabled: {
    opacity: 0.3,
  },
  navButtonText: {
    color: colors.text,
    fontSize: 15,
    fontWeight: '600',
  },
  progressDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: colors.lightGrey,
    marginHorizontal: 3,
  },
  progressDotActive: {
    backgroundColor: colors.primary,
    width: 20,
    borderRadius: 4,
  },
  progressDotRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },

  actionRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 12,
    paddingBottom: 30,
  },
  editButton: {
    backgroundColor: colors.lightGrey,
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 24,
  },
  editButtonText: {
    color: colors.text,
    fontSize: 14,
    fontWeight: '600',
  },
  deleteButton: {
    backgroundColor: '#fff0f0',
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 24,
    borderWidth: 1,
    borderColor: colors.danger,
  },
  deleteButtonText: {
    color: colors.danger,
    fontSize: 14,
    fontWeight: '600',
  },

  emptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 40,
  },
  emptyTitle: {
    color: colors.text,
    fontSize: 20,
    fontWeight: 'bold',
    marginBottom: 10,
    textAlign: 'center',
  },
  emptySubtitle: {
    color: colors.grey,
    fontSize: 15,
    textAlign: 'center',
    lineHeight: 22,
  },

  formContainer: {
    flex: 1,
    backgroundColor: colors.background,
    paddingHorizontal: 20,
    paddingTop: 50,
  },
  formHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 32,
  },
  backButton: {
    marginRight: 16,
    padding: 4,
  },
  backButtonText: {
    color: colors.primary,
    fontSize: 16,
    fontWeight: '600',
  },
  formTitle: {
    color: colors.text,
    fontSize: 22,
    fontWeight: 'bold',
  },
  label: {
    color: colors.grey,
    fontSize: 13,
    fontWeight: '600',
    letterSpacing: 1,
    textTransform: 'uppercase',
    marginBottom: 8,
  },
  input: {
    backgroundColor: colors.card,
    borderRadius: 12,
    padding: 16,
    color: colors.text,
    fontSize: 16,
    borderWidth: 1,
    borderColor: colors.border,
    marginBottom: 20,
  },
  textArea: {
    minHeight: 120,
    textAlignVertical: 'top',
  },
  saveButton: {
    backgroundColor: colors.primary,
    borderRadius: 12,
    paddingVertical: 16,
    alignItems: 'center',
    marginTop: 8,
  },
  saveButtonText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: 'bold',
  },
  errorText: {
    color: colors.danger,
    fontSize: 13,
    marginBottom: 12,
    marginTop: -14,
  },
});
